services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true                                  # To access to my Cyberpower USB UPS
    devices:
      - "/dev/bus/usb/001/002:/dev/bus/usb/001/002"   # Here is my Cyberpower UPS USB path (found via lsusb cmd)
    volumes:
      - /dev:/dev
      - /tmp/metrics:/tmp/metrics                     # Shared directory for Prometheus metrics
    depends_on:
      - redis
      - mongodb
      - nginx
    environment:
      - MY_UPS_ID_VENDOR=0764
      - MY_UPS_ID_PRODUCT=0601
      - prometheus_multiproc_dir=/tmp/metrics         # Config for Prometheus multiprocessing
    ports:
      - "8080:8080"                                   # To expose Prometheus metrics

  redis:
    image: "redis:6.0.16"

  mongodb:
    image: "mongo:4.4.8"
    environment:
      - MONGO_INITDB_DATABASE=mongodb

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
      - ./prometheus/recording_rules.yml:/etc/prometheus/recording_rules.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin 
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
    driver: local
