global:
  scrape_interval: 15s  
  evaluation_interval: 15s  
  
scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['webserver:8080'] 

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
      
rule_files:
  - "/etc/prometheus/alerts.yml"
  - "/etc/prometheus/recording_rules.yml"
